const testClasses = [
    {
       "CS-115 2187 2643":
       [
          {
             "term":"2187",
             "subject":"CS",
             "catalog":"115",
             "course_title":"Programming I",
             "department":"Computer Science",
             "enrol_capacity":22,
             "enrol_capacity_edited":22,
             "ge_designation":"GEB3",
             "class_number":2643,
             "combined_class_number":2643,
             "units":4,
             "schdlr_class_number":"2643",
             "schdlr_combined_class_number":"2643",
             "cb_is_new":0,
             "cb_is_deleted":0,
             "version":2,
             "revision":0,
             "cb_create_date":"2019-09-18T22:39:12.000Z",
             "cb_modified_date":"2019-09-18T22:39:12.000Z",
             "components":[
                "DIS",
                "LAB"
             ],
             "DIS":{
                "class_number":2643,
                "schdlr_class_number":"2643",
                "section":"001",
                "section_edited":"001",
                "component":"DIS",
                "class_type":"E",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"005060177",
                      "instructor_id_edited":"005060177",
                      "instructor_fName":"Gurman",
                      "instructor_lName":"Gill",
                      "wtu":3,
                      "wtu_edited":3,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"09:20:00",
                      "end_time":"10:35:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"09:20:00",
                      "end_time_edited":"10:35:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"09:20:00",
                      "end_time":"10:35:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"09:20:00",
                      "end_time_edited":"10:35:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             },
             "LAB":{
                "class_number":2644,
                "schdlr_class_number":"2644",
                "section":"002",
                "section_edited":"002",
                "component":"LAB",
                "class_type":"N",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"005060177",
                      "instructor_id_edited":"005060177",
                      "instructor_fName":"Gurman",
                      "instructor_lName":"Gill",
                      "wtu":2,
                      "wtu_edited":2,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"T",
                      "start_time":"14:00:00",
                      "end_time":"16:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"T",
                      "start_time_edited":"14:00:00",
                      "end_time_edited":"16:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"T",
                      "start_time":"14:00:00",
                      "end_time":"16:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"T",
                      "start_time_edited":"14:00:00",
                      "end_time_edited":"16:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             }
          },
          {
             "term":"2187",
             "subject":"CS",
             "catalog":"115",
             "course_title":"Programming I",
             "department":"Computer Science",
             "enrol_capacity":22,
             "enrol_capacity_edited":22,
             "ge_designation":"GEB3",
             "class_number":2645,
             "combined_class_number":2643,
             "units":4,
             "schdlr_class_number":"2645",
             "schdlr_combined_class_number":"2643",
             "cb_is_new":0,
             "cb_is_deleted":0,
             "version":2,
             "revision":0,
             "cb_create_date":"2019-09-18T22:39:12.000Z",
             "cb_modified_date":"2019-09-18T22:39:12.000Z",
             "components":[
                "DIS",
                "LAB"
             ],
             "DIS":{
                "class_number":2645,
                "schdlr_class_number":"2645",
                "section":"003",
                "section_edited":"003",
                "component":"DIS",
                "class_type":"E",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"005060177",
                      "instructor_id_edited":"005060177",
                      "instructor_fName":"Gurman",
                      "instructor_lName":"Gill",
                      "wtu":0,
                      "wtu_edited":0,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"09:20:00",
                      "end_time":"10:35:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"09:20:00",
                      "end_time_edited":"10:35:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"09:20:00",
                      "end_time":"10:35:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"09:20:00",
                      "end_time_edited":"10:35:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             },
             "LAB":{
                "class_number":2646,
                "schdlr_class_number":"2646",
                "section":"004",
                "section_edited":"004",
                "component":"LAB",
                "class_type":"N",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"001729837",
                      "instructor_id_edited":"001729837",
                      "instructor_fName":"Noah",
                      "instructor_lName":"Melcon",
                      "wtu":2,
                      "wtu_edited":2,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"T",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"T",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"T",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"T",
                      "start_time_edited":"14:00:00",
                      "end_time_edited":"16:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   },
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"T",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"T",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             }
          },
          {
             "term":"2187",
             "subject":"CS",
             "catalog":"115",
             "course_title":"Programming I",
             "department":"Computer Science",
             "enrol_capacity":24,
             "enrol_capacity_edited":24,
             "ge_designation":"GEB3",
             "class_number":3620,
             "combined_class_number":2643,
             "units":4,
             "schdlr_class_number":"3620",
             "schdlr_combined_class_number":"2643",
             "cb_is_new":0,
             "cb_is_deleted":0,
             "version":2,
             "revision":0,
             "cb_create_date":"2019-09-18T22:39:12.000Z",
             "cb_modified_date":"2019-09-18T22:39:12.000Z",
             "components":[
                "DIS",
                "LAB"
             ],
             "DIS":{
                "class_number":3620,
                "schdlr_class_number":"3620",
                "section":"009",
                "section_edited":"009",
                "component":"DIS",
                "class_type":"E",
                "req_room_capacity":24,
                "req_room_capacity_edited":24,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"005060177",
                      "instructor_id_edited":"005060177",
                      "instructor_fName":"Gurman",
                      "instructor_lName":"Gill",
                      "wtu":0,
                      "wtu_edited":0,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"09:20:00",
                      "end_time":"10:35:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"09:20:00",
                      "end_time_edited":"10:35:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"09:20:00",
                      "end_time":"10:35:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"09:20:00",
                      "end_time_edited":"10:35:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             },
             "LAB":{
                "class_number":3621,
                "schdlr_class_number":"3621",
                "section":"010",
                "section_edited":"010",
                "component":"LAB",
                "class_type":"N",
                "req_room_capacity":24,
                "req_room_capacity_edited":24,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"004522913",
                      "instructor_id_edited":"004522913",
                      "instructor_fName":"Tyler",
                      "instructor_lName":"Holland",
                      "wtu":2,
                      "wtu_edited":2,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"STEV1034",
                      "meeting_pattern":"W",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"STEV1034",
                      "meeting_pattern_edited":"W",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"STEV1034",
                      "meeting_pattern":"W",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"STEV1034",
                      "meeting_pattern_edited":"W",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             }
          }
       ],
    },
    {
       "CS-115 2187 3393":
       [
          {
             "term":"2187",
             "subject":"CS",
             "catalog":"115",
             "course_title":"Programming I",
             "department":"Computer Science",
             "enrol_capacity":22,
             "enrol_capacity_edited":22,
             "ge_designation":"GEB3",
             "class_number":3393,
             "combined_class_number":3393,
             "units":4,
             "schdlr_class_number":"3393",
             "schdlr_combined_class_number":"3393",
             "cb_is_new":0,
             "cb_is_deleted":0,
             "version":2,
             "revision":0,
             "cb_create_date":"2019-09-18T22:39:12.000Z",
             "cb_modified_date":"2019-09-18T22:39:12.000Z",
             "components":[
                "DIS",
                "LAB"
             ],
             "DIS":{
                "class_number":3393,
                "schdlr_class_number":"3393",
                "section":"005",
                "section_edited":"005",
                "component":"DIS",
                "class_type":"E",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"005060177",
                      "instructor_id_edited":"005060177",
                      "instructor_fName":"Gurman",
                      "instructor_lName":"Gill",
                      "wtu":3,
                      "wtu_edited":3,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"10:45:00",
                      "end_time":"12:00:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"10:45:00",
                      "end_time_edited":"12:00:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"10:45:00",
                      "end_time":"12:00:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"10:45:00",
                      "end_time_edited":"12:00:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             },
             "LAB":{
                "class_number":3394,
                "schdlr_class_number":"3394",
                "section":"006",
                "section_edited":"006",
                "component":"LAB",
                "class_type":"N",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"003114181",
                      "instructor_id_edited":"003114181",
                      "instructor_fName":"Kelsey",
                      "instructor_lName":"Rangel",
                      "wtu":2,
                      "wtu_edited":2,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"DARW0025",
                      "meeting_pattern":"W",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0025",
                      "meeting_pattern_edited":"W",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":24,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"DARW0025",
                      "meeting_pattern":"W",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0025",
                      "meeting_pattern_edited":"W",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":24,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             }
          },
          {
             "term":"2187",
             "subject":"CS",
             "catalog":"115",
             "course_title":"Programming I",
             "department":"Computer Science",
             "enrol_capacity":24,
             "enrol_capacity_edited":24,
             "ge_designation":"GEB3",
             "class_number":3618,
             "combined_class_number":3393,
             "units":4,
             "schdlr_class_number":"3618",
             "schdlr_combined_class_number":"3393",
             "cb_is_new":0,
             "cb_is_deleted":0,
             "version":2,
             "revision":0,
             "cb_create_date":"2019-09-18T22:39:12.000Z",
             "cb_modified_date":"2019-09-18T22:39:12.000Z",
             "components":[
                "DIS",
                "LAB"
             ],
             "DIS":{
                "class_number":3618,
                "schdlr_class_number":"3618",
                "section":"007",
                "section_edited":"007",
                "component":"DIS",
                "class_type":"E",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"005060177",
                      "instructor_id_edited":"005060177",
                      "instructor_fName":"Gurman",
                      "instructor_lName":"Gill",
                      "wtu":0,
                      "wtu_edited":0,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"10:45:00",
                      "end_time":"12:00:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"10:45:00",
                      "end_time_edited":"12:00:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"ZINFANDEL",
                      "meeting_pattern":"TTH",
                      "start_time":"10:45:00",
                      "end_time":"12:00:00",
                      "facility_name_edited":"ZINFANDEL",
                      "meeting_pattern_edited":"TTH",
                      "start_time_edited":"10:45:00",
                      "end_time_edited":"12:00:00",
                      "facility_cap":120,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             },
             "LAB":{
                "class_number":3619,
                "schdlr_class_number":"3619",
                "section":"008",
                "section_edited":"008",
                "component":"LAB",
                "class_type":"N",
                "req_room_capacity":25,
                "req_room_capacity_edited":25,
                "cc_is_new":0,
                "cc_is_deleted":0,
                "cc_create_date":"2019-09-18T22:39:12.000Z",
                "cc_modified_date":"2019-09-18T22:39:12.000Z",
                "instructors":[
                   {
                      "instructor_id":"001729837",
                      "instructor_id_edited":"001729837",
                      "instructor_fName":"Noah",
                      "instructor_lName":"Melcon",
                      "wtu":2,
                      "wtu_edited":2,
                      "ci_is_new":0,
                      "ci_is_deleted":0,
                      "ci_create_date":"2019-09-18T22:39:12.000Z",
                      "ci_modified_date":"2019-09-18T22:39:12.000Z"
                   }
                ],
                "meeting_pattern":[
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"W",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"W",
                      "start_time_edited":"17:00:00",
                      "end_time_edited":"19:50:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-18T22:39:12.000Z",
                      "mp_modified_date":"2019-09-18T22:39:12.000Z"
                   },
                   {
                      "facility_name":"DARW0028",
                      "meeting_pattern":"W",
                      "start_time":"17:00:00",
                      "end_time":"19:50:00",
                      "facility_name_edited":"DARW0028",
                      "meeting_pattern_edited":"TH",
                      "start_time_edited":"16:55:00",
                      "end_time_edited":"19:45:00",
                      "facility_cap":25,
                      "mp_is_new":0,
                      "mp_is_deleted":0,
                      "mp_create_date":"2019-09-19T05:39:12.000Z",
                      "mp_modified_date":"2019-09-19T05:39:12.000Z"
                   }
                ]
             }
          }
       ]
    }
 ];
 
 export default testClasses;